### ISSUE TITLE
Quote window specific chance

### ISSUE THREAD

**Issue by Pecomica** [JacobMcAuley/foundry-patrol#14]
When on patrol the token have a chance to say something either on patrol, when seeing player, or seeing any 'NPC' but the chance of that is the global setting in the moduel

Propose that each chat have a chance setting so on patrol it might not say much, 10% chance. 
when encountering a player it might say something 80% of the time
and when passing by a NPC it might greet them 40% of the time.

**Comment by JacobMcAuley** [comment]
Marked for release with 2.2.0
