### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by HippyCraig** [JacobMcAuley/foundry-patrol#20]
In your readme file you mention a new version being developed, is there a link to that project?

**Comment by JacobMcAuley** [comment]
Hi Craig!
There is a new version being developed, but at this time there is no openly available link.
I've been side tracked by this project: https://www.reddit.com/r/FoundryVTT/comments/m4laqb/macronomicon_a_new_way_to_create_macros/

Which is slated to release for Alpha soon.

Following the release of the above project, I will begin to resume work on the new version of Foundry Patrol.

Best,
Jacob

**Comment by HippyCraig** [comment]
That looks super cool, good luck with it!
