### ISSUE TITLE
Token does not move smoothly even with the option turned on

### ISSUE THREAD

**Issue by denyrj83** [JacobMcAuley/foundry-patrol#21]
**Describe the bug**
I use foundry version 0.8.8 and even with the smothy movement option enabled, the token moves by jumping between the grids.
Ps- I don't use grid in the scenes.

**To Reproduce**
1. place any icon to patrol with smooth motion

**Expected behavior**
that the token has a smooth move when patrolling.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome, but I'm using it on the client
 - Version [e.g. 22] Foundry 0.8.8

**Additional context**

**Comment by JacobMcAuley** [comment]
Hi,

This module is defunct. You should consider checking out this module: https://foundryvtt.com/packages/patrol
which should do what you're looking for.
