### ISSUE TITLE
Compatibility issue with 0.6.1 [fix inside]

### ISSUE THREAD

**Issue by apoapostolov** [JacobMcAuley/foundry-patrol#9]
With 0.6.1 released on 31/5, setting-extender.js has critical compatibility issue that prevents users from accessing the Settings in their Foundry if even one activated mod has the old settings-extender.js. I checked the mods that haven't been fixed yet and use setting-extender.js and wanted to let you know that @Azzurite has released a fixed version, all you need to do is replace and re-publish. From the Discord release post:
settings-extender 1.1.3

Link: https://gitlab.com/foundry-azzurite/settings-extender/
Direct Download: https://gitlab.com/foundry-azzurite/settings-extender/-/raw/1.1.3/src/settings-extender.js

Fixes a compatibility issue with 0.6.1. Module authors have to update their usage of this. If you're a user and want to use your favorite modules on 0.6.1 immediately, you have to either wait for them or manually replace one of your settings-extender.js files (only one is enough, the fix will be applied to all of them) with this.

**Comment by JacobMcAuley** [comment]
Thank you
Resolved!
